### ISSUE TITLE
Could not find a declaration type for model "shuffle letters".

### ISSUE THREAD

**Issue by WideCircle** [georapbox/shuffle-letters#1]
As the title says I have problems using this.
I use:
`const shuffleLetters = require('shuffle-letters');`

When I try to reinstall the package I get  error message that says the package doesn't exist...
Any ideas?

**Comment by georapbox** [comment]
Hi @WideCircle 

There is a typo regarding the instructions in README for requiring the CommonJS export.

It should be `const shuffleLetters = require('shuffle-letters').default;` instead of just `const shuffleLetters = require('shuffle-letters');` So, if you just import it this way, it should do the trick.

This is due to some quirks regarding how Rollup creates the CommonJS bundle when there is a `default` export in the source code. And in this case, the library is exported like this: `export default shuffleLetters;`.

Having said that, I will correct the documentation to use the correct instructions.

Please let me know if this works.
